server:
  port: ${PORT:8082}
  servlet:
    context-path: /api

spring:
  application:
    name: ai-ppap-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_ppap}
    username: ${DB_USER:ai_ppap}
    password: ${DB_PASS:ai_ppap}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5200,http://localhost:3000,http://127.0.0.1:5200,http://127.0.0.1:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    com.ai.pat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
